import { canonicalJson, verifyEd25519 } from '../src/crypto_verify';

// Vector generated by the Python IAP signer:
//   json.dumps(payload, sort_keys=True, separators=(",",":"), ensure_ascii=True)
//   then Ed25519-signed. Proves byte-for-byte canonicalization parity,
//   including non-ASCII (ensure_ascii) escaping and float formatting.
const payload = {
  plan_hash: 'abc123',
  issued_at: 1700000000.5,
  expires_at: 1700000060.5,
  policy: { allowed_tools: ['search', 'réad'], deny: [] },
  identity: 'agent@armoriq.io',
  public_key: 'e23dbe8dbb842eef51a8d7dba01019814e5e6eaa29936fe5aca3570b78bbd5f8',
  version: '1.0',
};
const PUBLIC_KEY = 'e23dbe8dbb842eef51a8d7dba01019814e5e6eaa29936fe5aca3570b78bbd5f8';
const SIGNATURE =
  '61c5a5169165d208fa3486b72262b5f0f9ae3c1f473379f9d6b729c2a3d6eb6c244caf14814b3e81930fed867f4f832eed5421ecd6db525428c92416b9818307';
const PY_CANONICAL =
  '{"expires_at":1700000060.5,"identity":"agent@armoriq.io","issued_at":1700000000.5,"plan_hash":"abc123","policy":{"allowed_tools":["search","r\\u00e9ad"],"deny":[]},"public_key":"e23dbe8dbb842eef51a8d7dba01019814e5e6eaa29936fe5aca3570b78bbd5f8","version":"1.0"}';

describe('canonicalJson', () => {
  it('matches Python json.dumps(sort_keys, compact, ensure_ascii) byte-for-byte', () => {
    expect(canonicalJson(payload)).toBe(PY_CANONICAL);
  });
  it('escapes non-ASCII as \\uXXXX', () => {
    expect(canonicalJson({ a: 'é' })).toBe('{"a":"\\u00e9"}');
  });
  it('rejects non-finite numbers', () => {
    expect(() => canonicalJson({ x: NaN })).toThrow();
  });
});

describe('verifyEd25519', () => {
  it('verifies a genuine Python-signed canonical payload', () => {
    const msg = Buffer.from(canonicalJson(payload), 'utf8');
    expect(verifyEd25519(PUBLIC_KEY, msg, SIGNATURE)).toBe(true);
  });
  it('rejects a tampered planHash', () => {
    const tampered = { ...payload, plan_hash: 'deadbeef' };
    const msg = Buffer.from(canonicalJson(tampered), 'utf8');
    expect(verifyEd25519(PUBLIC_KEY, msg, SIGNATURE)).toBe(false);
  });
  it('rejects malformed key/signature lengths', () => {
    const msg = Buffer.from('x', 'utf8');
    expect(verifyEd25519('00', msg, SIGNATURE)).toBe(false);
    expect(verifyEd25519(PUBLIC_KEY, msg, 'ab')).toBe(false);
  });
});
